version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: ianorth-backend
    restart: always
    ports:
      - "8030:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/ianorth_local.db:/app/ianorth_local.db
      - ./backend/src/static:/app/src/static
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "agi:10.6.0.36"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://192.168.1.82:8030"
    container_name: ianorth-frontend
    restart: always
    ports:
      - "8020:80"
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  # cubagem:
  #   build:
  #     context: ../lpr-sucata-ianorth/projeto_cubagem
  #     dockerfile: Dockerfile
  #   container_name: ianorth-cubagem
  #   restart: always
  #   ports:
  #     - "8031:8031"
  #   environment:
  #     - TZ=America/Sao_Paulo
  #     - CUBAGEM_INTERFACE_URL=http://backend:8000
  #   depends_on:
  #     - backend
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #         - capabilities: [gpu]
